### ISSUE TITLE
Please add some screenshot of your custom context menu so we can preview before installing it

### ISSUE THREAD

**Issue by KParthSingh** [hboyd2003/NanaZipAlternativeContextMenu#1]
thanks,

**Comment by hboyd2003** [comment]
@KParthSingh I'm sorry but I do not actually use this any more and it has a few issues with it so I would not recommend using it. I have moved onto [Nilesoft Shell](https://github.com/moudey/Shell) instead of ShellAnything. I will upload the config for that in a bit.

I meant to archive it.
